version: '3.7'
services:
  freshrss:
    image: linuxserver/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    volumes:
      - ../Data/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.freshrss.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.freshrss.entrypoints=web-secure"
      - "traefik.http.routers.freshrss.middlewares=default-headers@file"
      - "traefik.http.routers.freshrss.service=freshrss"
      - "traefik.http.routers.freshrss.tls=true"
      - "traefik.http.services.freshrss.loadbalancer.server.port=80" # Proxied Port
